stages:
  - lint

before_script:
  - mkdir ~/.aws
  - |
    cat <<EOF > ~/.aws/credentials
    [default]
    aws_access_key_id = ${DELOITTE_DEV_AWS_ACCESS_KEY_ID}
    aws_secret_access_key = ${DELOITTE_DEV_AWS_SECRET_ACCESS_KEY}
    EOF

terraform fmt:
  stage: lint
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - terraform fmt -diff -check

tflint:
  stage: lint
  image:
    name: wata727/tflint
    entrypoint:
      - /usr/bin/env
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  script:
    - tflint --deep